#version: "3.8"

services:
  ####### NGINX #######
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:80"
    expose:
      - "81"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - gateway_logs:/var/log/nginx
      - gateway_certs:/etc/nginx/certs

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
  
  ####### NGINX EXPORTER #######
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - "--nginx.scrape-uri=http://gateway:81/stub_status"
    networks:
      - internal
    expose:
      - "9113"
    depends_on:
      - gateway
    
  ####### BLACKBOX EXPORTER #######
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./metrics/blackbox/blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    networks:
      - internal
    expose:
      - "9115"
    depends_on:
      - gateway
    
  ####### PROMETHEUS #######
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - internal
    depends_on:
      - nginx_exporter

networks:
  internal:

volumes:
  gateway_logs:
  gateway_certs:
